# dockerの設定を記載しているのがymlである
# dockerの起動方法
# 1. docker desktopを起動する
# 2. vscodeのdocker-cpmpose.ymlを右クリック、compose upをクリック
# 3.A5mk2を起動、任意のデータベースの名前で右クリック、データベースの追加と削除、テスト接続がOKならつながっている
# 終了時
# vscodeのdocker-cpmpose.ymlを右クリック、compose downをクリック


version: "3"
services:
  db:
    image: postgres:10
    container_name: "db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmanage
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  database:
    driver: local